name = "fetch-rs-dev"
#type = "rust"
compatibility_date = "2022-08-16"
account_id = "9ddca7c9df604668fc6d14f079b2f066" 
workers_dev = false
#route = ""
#zone_id = ""
main = "build/worker/shim.mjs"
# main = "pkg"
 

[env.production]
# exclude = ["node_modules","*"]
# include = ["dist/*","src/*"]
name = "fetch-rs" #fetch-rs.mastercard-backbank.backbank.workers.dev
#route = "https://sausage.saltbank.org/api*"
route = { pattern = "https://api.saltbank.org/*", zone_id = "6202e995eadc857cd8e97e8ba608286d" }

[build]
command = "worker-build --release"
#command = "./worker-build --release" permission denied, perhaps command by github action
#command = "target/release --release" 
# command = "wasm-pack build --target web"
