name: dispatch receiver

on: [repository_dispatch]
  #repository_dispatch:
  #schedule:
    #- cron: '5 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #main
    - name: curlable
      #with:
        #fetch-depth: 1
        #token: ${{ secrets.GITHUB_TOKEN }}
      # if: github.event.action == "YOUR_EVENT_TYPE" # https://docs.github.com/en/rest/actions set action
      run: |
        echo "repository_dispatch triggered"
